name: "Run a Reflect Test Suite"
description: "Run a Reflect (https://reflect.run) test suite"
author: "John Brooks <jbrooks@sandstormdesign.com>"
inputs:
  api-key:
    description: "Your Reflect API key (https://app.reflect.run/settings/account)"
    required: true
  suite-id:
    description: "The ID of the test to run"
    required: true
  variables:
    description: "A YAML document of ('name', 'definition') variable overrides to apply to this scheduled execution"
    required: false
  wait-for-completion:
    description: Wait for the test to complete before continuing
    required: false
    default: true
outputs:
  execution:
    description: "A JSON object containing the execution details"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: check-circle
  color: green
